### ISSUE TITLE
ImportError: No module named gtk

### ISSUE THREAD

**Issue by seamus-45** [boothj5/profanity-plugins#4] opened 2016-04-11 06:08 UTC
Greetings, I modified code of paste.py plugin for using pygtk instead of tkinter, because I have its already installed. But I get error mentioned in subject:
```
11/04/2016 10:15:33: stderr: ERR: Traceback (most recent call last):
11/04/2016 10:15:33: stderr: ERR:   File "/home/user/.local/share/profanity/plugins/paste.py", line 6, in <module>
11/04/2016 10:15:33: stderr: ERR:     import gtk
11/04/2016 10:15:33: stderr: ERR: ImportError: No module named gtk

```
Module pygtk installed in system, and can be succesfully imported in **IPython**.

Code of modified plugin:
https://gist.github.com/seamus-45/b35ce7e8b1fe80fa51da8c2cc418f7a0

```
Profanity, version 0.5.0dev.branch-master.699e08b
Copyright (C) 2012 - 2016 James Booth <boothj5web@gmail.com>.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Build information:
XMPP library: libstrophe
Desktop notification support: Enabled
OTR support: Disabled
PGP support: Disabled
C plugins: Enabled
Python plugins: Enabled
```

What am I doing wrong?

**Comment by boothj5** [comment] 2016-04-11 12:06
Is it just GTK you're having issues with?  I.e. can you import any other third party packages into a plugin?

Also, I don't know much about the Python GTK implementation but importing seems to be slightly complicated... http://stackoverflow.com/questions/22095537/how-do-i-import-gtk-module-to-my-application-python

**Comment by seamus-45** [comment] 2016-04-11 12:27
I can run without problems this code and its work:
```python
~ ❯❯❯ echo 'hello world' | xclip                                                                master ✱
~ ❯❯❯ cat paste.py                                                                              master ✱
import gtk


def _cmd_paste():
    clipboard = gtk.clipboard_get(selection="PRIMARY")
    result = clipboard.wait_for_text()
    print result

_cmd_paste()
~ ❯❯❯ python ./paste.py                                                                      master ✱
hello world

```

I have no idea why gtk module is not imported from profanity

**Comment by boothj5** [comment] 2016-04-11 23:59
Managed to recreate and find what the problem is, but I haven't found a fix yet.

When profanity initialises the Python interpreter it just adds the `site-packages` and/or `dist-packages` folders to the `sys.path` so any modules directly in those folders can be imported by plugins.  However, on my system the `gtk` module is in:

```
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk
```

Since the interpreter has been set up to only look in `/usr/lib/python2.7/dist-packages/` (on my machine) its not finding `gtk`, and you obviously have the same issue but with `site-packages`.

I have a couple of ideas how to fix it, will update this issue once resolved.

**Comment by boothj5** [comment] 2016-04-12 01:34
I've attempted a fix, it's in a `python-path` branch of profanity until I've tested it's not broken anything else.

If you have a chance to build this branch, let me know if your plugin works.

**Comment by seamus-45** [comment] 2016-04-12 04:58
Thanks, it works. But [code](https://github.com/boothj5/profanity/commit/8ff9fd709114c7e24f1c3a4019fc3afd1e3809ec) looks strange. I found similar solution on [stackoverflow](https://stackoverflow.com/questions/7137412/python-c-api-modify-search-path). May be better use method mentioned in first answer, instead of execute python string?

**Comment by boothj5** [comment] 2016-04-12 09:03
Great, thanks.

What do you find strange about the code?

Using the C-Python API in this case seemed a bit like overkill to me as it involves getting attributes, checking something is callable, creating an object to represent the string argument, using a build value to build the arguments, then doing a call object etc most of which is not actually mentioned in the first post in your link.

Given that I'm not interacting with any plugins and just need to execute some arbitrary python code, the simple string seemed like a better option...

**Comment by seamus-45** [comment] 2016-04-12 09:10
Ok, sorry for the inappropriate comment, i am not C programmer, and just ask :) For me, a little strange to see the interpreted code in a С source code. We can close this issue?

**Comment by boothj5** [comment] 2016-04-12 09:13
No problem, just wanted to check I hadn't missed something.

I'll close after merging to master.

And thanks for pointing this one out, it would have caused a problem for a lot of other libraries too.

**Comment by boothj5** [comment] 2016-04-12 22:01
Merged to master.

**Closed by boothj5** 2016-04-12 22:01 UTC
